apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replication-pod
  labels:
    app: my-app
    type: frontend
spec:
  template:
    metadata:
      name: app-pod
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend
